### ISSUE TITLE
点击删除没反应

### ISSUE THREAD

**Issue by h3zh1** [aqiongbei/qzone_helper#12]
![image](https://user-images.githubusercontent.com/68958533/107019699-f5d86e00-67dc-11eb-91d7-b2ae24641683.png)

**Comment by aqiongbei** [comment]
多数情况是由[issues#11](https://github.com/aqiongbei/qzone_helper/issues/11)导致的,现已经修复.

**Comment by 2698409414** [comment]
大哥没有自定义删除想删除的吗，只有全删吗

**Comment by aqiongbei** [comment]
> 大哥没有自定义删除想删除的吗，只有全删吗

现在只有全删

**Comment by 2698409414** [comment]
好的，删除的时候有验证码，怎么解决呢。

**Comment by aqiongbei** [comment]
> 好的，删除的时候有验证码，怎么解决呢。

页面点击删除遇到验证码还是用这个插件删除时候碰到了验证码
