### ISSUE TITLE
点击删除没反应

### ISSUE THREAD

**Issue by edwardyeung** [aqiongbei/qzone_helper#14]
![QQ截图20220124003849](https://user-images.githubusercontent.com/8679356/150705123-33f8d76a-e01a-463a-b974-e690059b934b.png)

**Comment by edwardyeung** [comment]
用的是edge 97.0.1072.69 (官方内部版本) (64 位)
系统是 windows 10 19042.1466
人在海外。不知道跟这个有没有关系。看情况是连接不上。

**Comment by aqiongbei** [comment]
记下了，有空我排查下

**Comment by dfmjndm** [comment]
已失效

**Comment by DanielSun11** [comment]
所有button均无响应

**Comment by xin929-sudo** [comment]
![Uploading P02R[W`YKCP{{R]%[H~SA75.png…]()
 点不动

**Comment by aqiongbei** [comment]
改了一版，修复了
