### ISSUE TITLE
删除说说时控制台报错，Uncaught TypeError: QZONE.FP.showMsgbox(...) is not a function

### ISSUE THREAD

**Issue by JoshuaYang** [aqiongbei/qzone_helper#2]
Uncaught TypeError: QZONE.FP.showMsgbox(...) is not a function
    at deleteMsg (<anonymous>:52:9)
    at QZFL.JSONGetter._loader.onSuccess (<anonymous>:229:24)

看了一下，在代码51、52行报错

**Comment by JoshuaYang** [comment]
<img width="789" alt="wx20180228-101514 2x" src="https://user-images.githubusercontent.com/5389166/36766312-493851de-1c70-11e8-8785-d2f20454ce1e.png">

**Comment by yuxincs** [comment]
也许回复有点晚，不过遇到同样的问题，在QZONE.FP.showMsg那一行后面加一个分号就行了。
reference:
https://stackoverflow.com/questions/31013221/typeerror-console-log-is-not-a-function

**Comment by JoshuaYang** [comment]
后来自己写了个爬虫删掉了。。。依旧感谢

**Comment by yuxincs** [comment]
代码能分享吗？这个代码仍然会触发验证码 :/

**Comment by aqiongbei** [comment]
已更新,改用chrome 插件的形式来实现.欢迎试用.
